# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=30)),
                ('topLeft_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topLeft_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottomRight_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bottomRight_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisements_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('advertisement_name', models.CharField(default='', max_length=30)),
                ('advertisement_text', models.CharField(default='', max_length=200)),
                ('advertisement_areas', models.ManyToManyField(to='boothManagement.Advertisement_Area')),
            ],
        ),
        migrations.CreateModel(
            name='Booth_Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('boothName', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('owner_booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boothManagement.Booth_Owner')),
            ],
        ),
        migrations.AddField(
            model_name='advertisements_order',
            name='owner_booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boothManagement.Booth_Owner'),
        ),
    ]
