# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0001_initial'),
	]

	operations = [
		migrations.RenameField(
			model_name='booth_owner_profile',
			old_name='name',
			new_name='BoothName',
		),
	]
