# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='booth_details',
			name='id',
			field=models.AutoField(primary_key=True, serialize=False),
		),
	]
