# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0002_auto_20170315_0814'),
	]

	operations = [
		migrations.RenameModel(
			old_name='Booth_Owner_Profile',
			new_name='Booth_Owner',
		),
		migrations.RenameField(
			model_name='booth_owner',
			old_name='BoothName',
			new_name='boothName',
		),
	]
