# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0002_booth_owner_image'),
	]

	operations = [
		migrations.AddField(
			model_name='product_details',
			name='image',
			field=models.FileField(blank=True, default='default/mptr2-01.jpg', max_length=255, null=True, upload_to='images/%Y/%m/%d'),
		),
		migrations.AlterField(
			model_name='booth_owner',
			name='image',
			field=models.FileField(blank=True, default='default/profile-big.png', max_length=255, null=True, upload_to='images/%Y/%m/%d'),
		),
	]
