# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0002_auto_20170307_0923'),
	]

	operations = [
		migrations.CreateModel(
			name='Product_Details',
			fields=[
				('id', models.AutoField(primary_key=True, serialize=False)),
				('name', models.CharField(max_length=100)),
				('model', models.CharField(max_length=100)),
				('description', models.CharField(max_length=300)),
				('price', models.IntegerField()),
				('status', models.BooleanField(default=True)),
			],
		),
	]
