# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0003_product_details'),
	]

	operations = [
		migrations.AddField(
			model_name='product_details',
			name='owner_booth',
			field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boothManagement.Booth_Details'),
		),
	]
