# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0003_product_details_image_20170719_0923'),
	]

	operations = [
		migrations.AddField(
			model_name='advertisements_order',
			name='image',
			field=models.FileField(blank=True, default='default/advertise.jpg', max_length=255, null=True, upload_to='images/%Y/%m/%d'),
		),
	]
