# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0003_auto_20170315_1150'),
	]

	operations = [
		migrations.CreateModel(
			name='Advertisement_Area',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('section_name', models.CharField(max_length=30)),
				('topLeft_x', models.DecimalField(decimal_places=2, max_digits=5)),
				('topLeft_y', models.DecimalField(decimal_places=2, max_digits=5)),
				('bottomRight_x', models.DecimalField(decimal_places=2, max_digits=5)),
				('bottomRight_y', models.DecimalField(decimal_places=2, max_digits=5)),
				('base_price', models.IntegerField()),
			],
		),
	]
