# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('boothManagement', '0004_advertisement_area'),
	]

	operations = [
		migrations.CreateModel(
			name='Advertisements_order',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('totalPrice', models.IntegerField()),
				('discount', models.IntegerField(default=0)),
				('advertisement_name', models.CharField(default='', max_length=30)),
				('advertisement_text', models.CharField(default='', max_length=200)),
				('advertisement_areas', models.ManyToManyField(to='boothManagement.Advertisement_Area')),
			],
		),
	]
